2019-11-21 15:04:35,822 INFO: Microblog startup [in D:\microblog\app\__init__.py:27]
2019-11-21 15:05:04,309 INFO: Microblog startup [in D:\microblog\app\__init__.py:27]
2019-11-21 15:20:28,957 INFO: Microblog startup [in D:\microblog\app\__init__.py:27]
2019-11-21 15:20:43,417 INFO: Microblog startup [in D:\microblog\app\__init__.py:27]
2019-11-21 15:30:26,694 INFO: Microblog startup [in D:\microblog\app\__init__.py:27]
2019-11-21 15:31:16,025 INFO: Microblog startup [in D:\microblog\app\__init__.py:27]
2019-11-21 15:31:22,509 INFO: Microblog startup [in D:\microblog\app\__init__.py:27]
2019-11-21 15:31:40,199 INFO: Microblog startup [in D:\microblog\app\__init__.py:27]
2019-11-21 15:34:16,561 INFO: Microblog startup [in D:\microblog\app\__init__.py:27]
2019-11-21 15:41:46,777 INFO: Microblog startup [in D:\microblog\app\__init__.py:27]
2019-11-21 16:34:41,250 INFO: Microblog startup [in D:\microblog\app\__init__.py:27]
2019-11-21 16:34:48,697 INFO: Microblog startup [in D:\microblog\app\__init__.py:27]
2019-11-21 16:35:49,856 ERROR: Exception on /user/¹þ¹þ [GET] [in d:\microblog\venvname\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "d:\microblog\venvname\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\microblog\venvname\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\microblog\venvname\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\microblog\venvname\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\microblog\venvname\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\microblog\venvname\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\microblog\venvname\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\microblog\app\routes.py", line 38, in user
    return render_template('user.html', user=user, posts=posts)
  File "d:\microblog\venvname\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "d:\microblog\venvname\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "d:\microblog\venvname\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "d:\microblog\venvname\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "d:\microblog\venvname\lib\site-packages\jinja2\loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "d:\microblog\venvname\lib\site-packages\jinja2\environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "d:\microblog\venvname\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\microblog\venvname\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\microblog\app\templates\user.html", line 17, in <module>
    {% else %}
  File "d:\microblog\venvname\lib\site-packages\jinja2\environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "d:\microblog\venvname\lib\site-packages\jinja2\parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "d:\microblog\venvname\lib\site-packages\jinja2\parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "d:\microblog\venvname\lib\site-packages\jinja2\parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "d:\microblog\venvname\lib\site-packages\jinja2\parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "d:\microblog\venvname\lib\site-packages\jinja2\parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "d:\microblog\venvname\lib\site-packages\jinja2\parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "d:\microblog\venvname\lib\site-packages\jinja2\parser.py", line 144, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "d:\microblog\venvname\lib\site-packages\jinja2\parser.py", line 97, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "d:\microblog\venvname\lib\site-packages\jinja2\parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "d:\microblog\venvname\lib\site-packages\jinja2\parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'else'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2019-11-21 16:47:03,657 INFO: Microblog startup [in D:\microblog\app\__init__.py:27]
2019-11-21 17:27:05,100 INFO: Microblog startup [in D:\microblog\app\__init__.py:27]
